<?php

namespace App\Helpers;

class EmailHelper
{
    private static array $disposableDomains = [
        'mailinator.com', 'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
        'guerrillamail.biz', 'sharklasers.com', 'grr.la', 'guerrillamail.de',
        'tempmail.com', 'tempmail.net', 'temp-mail.org', 'tempemail.net',
        'throwaway.email', 'throwawaymail.com', 'throwawayemail.com',
        'trashmail.com', 'trashmail.net', 'trashmail.org', 'trashmail.ws',
        'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
        'yopmail.com', 'yopmail.net', 'yopmail.fr', 'yopmail.org',
        '10minutemail.com', '10minutemail.net', '10minutemail.org',
        'maildrop.cc', 'maildrop.net', 'maildrop.org',
        'getairmail.com', 'airmailhub.com', 'airmail.cc',
        'tempinbox.com', 'tempinbox.net', 'fakemail.net',
        'fakemailgenerator.com', 'fakemailgenerator.net',
        'mailcatch.com', 'mailmetrash.com', 'mailexpire.com',
        'sogetthis.com', 'soyoumail.com', 'thankyou2010.com',
        'emailias.com', 'emailsearcher.com', 'emailtemporario.com.br',
        'emailtemporarily.com', 'emailtemporario.net',
        'disposableemail.com', 'disposableemail.net',
        'dispostable.com', 'dispostable.net',
        'dumpmail.com', 'dumpmail.de', 'dumpmail.net',
        'emailondeck.com', 'emailondeck.net',
        'generator.email', 'generatormail.com', 'getnada.com',
        'inboxbear.com', 'inboxbear.net',
        'jetable.com', 'jetable.net', 'jetable.org',
        'mail-temp.com', 'maileater.com', 'mailnator.com',
        'mailsac.com', 'mailsac.net', 'mailsac.org',
        'mintemail.com', 'mohmal.com', 'mohmal.net',
        'mytrashmail.com', 'mytrashmail.net',
        'nowmymail.com', 'nowmymail.net',
        'oneoffemail.com', 'oneoffmail.com',
        'ovpn.to', 'proxymail.eu', 'quickinbox.com',
        'rcpt.at', 'receiveee.com', 'receiveee.net',
        'recycleemail.com', 'regbypass.com', 'regbypass.net',
        'selfdestructingmail.com', 'selfdestructingmail.net',
        'sendspamhere.com', 'sneakemail.com', 'sneakemail.net',
        'spambob.com', 'spambob.net', 'spambob.org',
        'spamex.com', 'spamfree24.org', 'spamfree24.net',
        'spamfree24.com', 'spamfree24.de',
        'spamhereplease.com', 'spamherelots.com',
        'spamhole.com', 'spaml.com', 'spammotel.com',
        'spamobox.com', 'spamslicer.com',
        'spamtrail.com', 'spamvert.com', 'spamwp.com',
        'speed1mail.com', 'spoofmail.com', 'spoofmail.de',
        'stopdropandroll.com', 'suioe.com', 'svxr.org',
        'sweetxxx.de', 'sylvannet.com', 'tafmail.com',
        'tagyourself.com', 'talkinator.com',
        'teleworm.com', 'teleworm.us', 'teewars.org',
        'tempail.com', 'tempalias.com', 'tempemail.co',
        'tempmail.co', 'tempomail.fr', 'temporaryemail.net',
        'temporaryforwarding.com', 'temporaryinbox.com',
        'thanksnospam.info', 'thanksnospam.net', 'thanksnospam.org',
        'thisisnotmyrealemail.com', 'throwaway.email',
        'tilien.com', 'tinymail.org', 'tittbit.org',
        'trash2009.com', 'trash-2009.com', 'trashymail.com',
        'trashymail.net', 'trashymail.org',
        'tyldd.com', 'uggsrock.com', 'wegwerfmail.de',
        'wegwerfmail.net', 'wegwerfmail.org',
        'wh4f.org', 'whyspam.me', 'willselfdestruct.com',
        'winemaven.info', 'wronghead.com', 'wuzup.net',
        'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com',
        'xoxy.net', 'yep.it', 'yogamaven.com', 'yopmail.fr',
        'yopmail.net', 'ypmail.webarnak.com',
        'zehnminutenmail.de', 'zehnminutenmail.net',
        'zippymail.info', 'zombie-hunter.com',
        'mailnator.com', 'mailinator2.com', 'mailinatorzz.com',
        'mailmetrash.com', 'mailmoat.com', 'mailquack.com',
        'mailtothis.com', 'mailzi.com', 'mailzilla.org',
        'mailzilla.com', 'mailzilla.net',
        'myinbox.xyz', 'mytrashmail.com', 'mytempemail.com',
        'mytsp.net', 'x5a.de', 'zero-e.ml', 'zepp.dk',
        'zetmail.com', 'zippymail.info', 'maildrop.cc',
        'maildu.de', 'maileater.com', 'mailexpire.com',
        'mailfa.tk', 'mailforspam.com', 'mailfreeonline.com',
        'mailhaven.com', 'mailin8r.com', 'mailinatar.com',
        'mailinator.pl', 'mailinator.co.uk', 'mailinator.com',
        'mailinator.info', 'mailinator.net', 'mailinator.org',
        'mailinator.us', 'mailinator2.com', 'mailinbox.co',
        'mailincubator.com', 'mailme.ir', 'mailme.lv',
        'mailmetrash.com', 'mailnator.com', 'mailnull.com',
        'mailsac.com', 'mailscrap.com', 'mailseal.de',
        'mailshell.com', 'mailsiphon.com', 'mailslapping.com',
        'mailsnails.com', 'mailtemporaire.com', 'mailtester.com',
    ];

    public static function isDisposable(string $email): bool
    {
        $domain = strtolower(substr(strrchr($email, '@'), 1));
        return in_array($domain, self::$disposableDomains, true);
    }
}
