<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['name' => 'Al-Fatiha', 'name_arabic' => 'الفاتحة', 'juz' => 1, 'hizb' => 1, 'verses_count' => 7, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Baqarah', 'name_arabic' => 'البقرة', 'juz' => 1, 'hizb' => 1, 'verses_count' => 286, 'revelation_type' => 'Medinan'],
            ['name' => 'Ali Imran', 'name_arabic' => 'آل عمران', 'juz' => 3, 'hizb' => 5, 'verses_count' => 200, 'revelation_type' => 'Medinan'],
            ['name' => 'An-Nisa', 'name_arabic' => 'النساء', 'juz' => 4, 'hizb' => 8, 'verses_count' => 176, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Maidah', 'name_arabic' => 'المائدة', 'juz' => 6, 'hizb' => 11, 'verses_count' => 120, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Anam', 'name_arabic' => 'الأنعام', 'juz' => 7, 'hizb' => 13, 'verses_count' => 165, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Araf', 'name_arabic' => 'الأعراف', 'juz' => 8, 'hizb' => 16, 'verses_count' => 206, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Anfal', 'name_arabic' => 'الأنفال', 'juz' => 9, 'hizb' => 18, 'verses_count' => 75, 'revelation_type' => 'Medinan'],
            ['name' => 'At-Tawbah', 'name_arabic' => 'التوبة', 'juz' => 10, 'hizb' => 20, 'verses_count' => 129, 'revelation_type' => 'Medinan'],
            ['name' => 'Yunus', 'name_arabic' => 'يونس', 'juz' => 11, 'hizb' => 21, 'verses_count' => 109, 'revelation_type' => 'Meccan'],
            ['name' => 'Hud', 'name_arabic' => 'هود', 'juz' => 11, 'hizb' => 22, 'verses_count' => 123, 'revelation_type' => 'Meccan'],
            ['name' => 'Yusuf', 'name_arabic' => 'يوسف', 'juz' => 12, 'hizb' => 24, 'verses_count' => 111, 'revelation_type' => 'Meccan'],
            ['name' => 'Ar-Rad', 'name_arabic' => 'الرعد', 'juz' => 13, 'hizb' => 25, 'verses_count' => 43, 'revelation_type' => 'Medinan'],
            ['name' => 'Ibrahim', 'name_arabic' => 'إبراهيم', 'juz' => 13, 'hizb' => 26, 'verses_count' => 52, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Hijr', 'name_arabic' => 'الحجر', 'juz' => 14, 'hizb' => 27, 'verses_count' => 99, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Nahl', 'name_arabic' => 'النحل', 'juz' => 14, 'hizb' => 28, 'verses_count' => 128, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Isra', 'name_arabic' => 'الإسراء', 'juz' => 15, 'hizb' => 30, 'verses_count' => 111, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Kahf', 'name_arabic' => 'الكهف', 'juz' => 15, 'hizb' => 30, 'verses_count' => 110, 'revelation_type' => 'Meccan'],
            ['name' => 'Maryam', 'name_arabic' => 'مريم', 'juz' => 16, 'hizb' => 31, 'verses_count' => 98, 'revelation_type' => 'Meccan'],
            ['name' => 'Ta-Ha', 'name_arabic' => 'طه', 'juz' => 16, 'hizb' => 32, 'verses_count' => 135, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Anbiya', 'name_arabic' => 'الأنبياء', 'juz' => 17, 'hizb' => 33, 'verses_count' => 112, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Hajj', 'name_arabic' => 'الحج', 'juz' => 17, 'hizb' => 34, 'verses_count' => 78, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Muminun', 'name_arabic' => 'المؤمنون', 'juz' => 18, 'hizb' => 35, 'verses_count' => 118, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Nur', 'name_arabic' => 'النور', 'juz' => 18, 'hizb' => 36, 'verses_count' => 64, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Furqan', 'name_arabic' => 'الفرقان', 'juz' => 18, 'hizb' => 36, 'verses_count' => 77, 'revelation_type' => 'Meccan'],
            ['name' => 'Ash-Shuara', 'name_arabic' => 'الشعراء', 'juz' => 19, 'hizb' => 37, 'verses_count' => 227, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Naml', 'name_arabic' => 'النمل', 'juz' => 19, 'hizb' => 38, 'verses_count' => 93, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qasas', 'name_arabic' => 'القصص', 'juz' => 20, 'hizb' => 39, 'verses_count' => 88, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ankabut', 'name_arabic' => 'العنكبوت', 'juz' => 20, 'hizb' => 40, 'verses_count' => 69, 'revelation_type' => 'Meccan'],
            ['name' => 'Ar-Rum', 'name_arabic' => 'الروم', 'juz' => 21, 'hizb' => 41, 'verses_count' => 60, 'revelation_type' => 'Meccan'],
            ['name' => 'Luqman', 'name_arabic' => 'لقمان', 'juz' => 21, 'hizb' => 41, 'verses_count' => 34, 'revelation_type' => 'Meccan'],
            ['name' => 'As-Sajdah', 'name_arabic' => 'السجدة', 'juz' => 21, 'hizb' => 42, 'verses_count' => 30, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ahzab', 'name_arabic' => 'الأحزاب', 'juz' => 21, 'hizb' => 42, 'verses_count' => 73, 'revelation_type' => 'Medinan'],
            ['name' => 'Saba', 'name_arabic' => 'سبأ', 'juz' => 22, 'hizb' => 43, 'verses_count' => 54, 'revelation_type' => 'Meccan'],
            ['name' => 'Fatir', 'name_arabic' => 'فاطر', 'juz' => 22, 'hizb' => 43, 'verses_count' => 45, 'revelation_type' => 'Meccan'],
            ['name' => 'Ya-Sin', 'name_arabic' => 'يس', 'juz' => 22, 'hizb' => 44, 'verses_count' => 83, 'revelation_type' => 'Meccan'],
            ['name' => 'As-Saffat', 'name_arabic' => 'الصافات', 'juz' => 23, 'hizb' => 45, 'verses_count' => 182, 'revelation_type' => 'Meccan'],
            ['name' => 'Sad', 'name_arabic' => 'ص', 'juz' => 23, 'hizb' => 45, 'verses_count' => 88, 'revelation_type' => 'Meccan'],
            ['name' => 'Az-Zumar', 'name_arabic' => 'الزمر', 'juz' => 23, 'hizb' => 46, 'verses_count' => 75, 'revelation_type' => 'Meccan'],
            ['name' => 'Ghafir', 'name_arabic' => 'غافر', 'juz' => 24, 'hizb' => 47, 'verses_count' => 85, 'revelation_type' => 'Meccan'],
            ['name' => 'Fussilat', 'name_arabic' => 'فصلت', 'juz' => 24, 'hizb' => 48, 'verses_count' => 54, 'revelation_type' => 'Meccan'],
            ['name' => 'Ash-Shura', 'name_arabic' => 'الشورى', 'juz' => 25, 'hizb' => 49, 'verses_count' => 53, 'revelation_type' => 'Meccan'],
            ['name' => 'Az-Zukhruf', 'name_arabic' => 'الزخرف', 'juz' => 25, 'hizb' => 49, 'verses_count' => 89, 'revelation_type' => 'Meccan'],
            ['name' => 'Ad-Dukhan', 'name_arabic' => 'الدخان', 'juz' => 25, 'hizb' => 50, 'verses_count' => 59, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Jathiyah', 'name_arabic' => 'الجاثية', 'juz' => 25, 'hizb' => 50, 'verses_count' => 37, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ahqaf', 'name_arabic' => 'الأحقاف', 'juz' => 26, 'hizb' => 51, 'verses_count' => 35, 'revelation_type' => 'Meccan'],
            ['name' => 'Muhammad', 'name_arabic' => 'محمد', 'juz' => 26, 'hizb' => 51, 'verses_count' => 38, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Fath', 'name_arabic' => 'الفتح', 'juz' => 26, 'hizb' => 52, 'verses_count' => 29, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Hujurat', 'name_arabic' => 'الحجرات', 'juz' => 26, 'hizb' => 52, 'verses_count' => 18, 'revelation_type' => 'Medinan'],
            ['name' => 'Qaf', 'name_arabic' => 'ق', 'juz' => 26, 'hizb' => 52, 'verses_count' => 45, 'revelation_type' => 'Meccan'],
            ['name' => 'Adh-Dhariyat', 'name_arabic' => 'الذاريات', 'juz' => 26, 'hizb' => 53, 'verses_count' => 60, 'revelation_type' => 'Meccan'],
            ['name' => 'At-Tur', 'name_arabic' => 'الطور', 'juz' => 27, 'hizb' => 53, 'verses_count' => 49, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Najm', 'name_arabic' => 'النجم', 'juz' => 27, 'hizb' => 53, 'verses_count' => 62, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qamar', 'name_arabic' => 'القمر', 'juz' => 27, 'hizb' => 54, 'verses_count' => 55, 'revelation_type' => 'Meccan'],
            ['name' => 'Ar-Rahman', 'name_arabic' => 'الرحمن', 'juz' => 27, 'hizb' => 54, 'verses_count' => 78, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Waqiah', 'name_arabic' => 'الواقعة', 'juz' => 27, 'hizb' => 54, 'verses_count' => 96, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Hadid', 'name_arabic' => 'الحديد', 'juz' => 27, 'hizb' => 55, 'verses_count' => 29, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Mujadilah', 'name_arabic' => 'المجادلة', 'juz' => 28, 'hizb' => 55, 'verses_count' => 22, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Hashr', 'name_arabic' => 'الحشر', 'juz' => 28, 'hizb' => 56, 'verses_count' => 24, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Mumtahanah', 'name_arabic' => 'الممتحنة', 'juz' => 28, 'hizb' => 56, 'verses_count' => 13, 'revelation_type' => 'Medinan'],
            ['name' => 'As-Saff', 'name_arabic' => 'الصف', 'juz' => 28, 'hizb' => 56, 'verses_count' => 14, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Jumuah', 'name_arabic' => 'الجمعة', 'juz' => 28, 'hizb' => 56, 'verses_count' => 11, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Munafiqun', 'name_arabic' => 'المنافقون', 'juz' => 28, 'hizb' => 57, 'verses_count' => 11, 'revelation_type' => 'Medinan'],
            ['name' => 'At-Taghabun', 'name_arabic' => 'التغابن', 'juz' => 28, 'hizb' => 57, 'verses_count' => 18, 'revelation_type' => 'Medinan'],
            ['name' => 'At-Talaq', 'name_arabic' => 'الطلاق', 'juz' => 28, 'hizb' => 57, 'verses_count' => 12, 'revelation_type' => 'Medinan'],
            ['name' => 'At-Tahrim', 'name_arabic' => 'التحريم', 'juz' => 28, 'hizb' => 57, 'verses_count' => 12, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Mulk', 'name_arabic' => 'الملك', 'juz' => 29, 'hizb' => 57, 'verses_count' => 30, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qalam', 'name_arabic' => 'القلم', 'juz' => 29, 'hizb' => 58, 'verses_count' => 52, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Haqqah', 'name_arabic' => 'الحاقة', 'juz' => 29, 'hizb' => 58, 'verses_count' => 52, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Maarij', 'name_arabic' => 'المعارج', 'juz' => 29, 'hizb' => 58, 'verses_count' => 44, 'revelation_type' => 'Meccan'],
            ['name' => 'Nuh', 'name_arabic' => 'نوح', 'juz' => 29, 'hizb' => 58, 'verses_count' => 28, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Jinn', 'name_arabic' => 'الجن', 'juz' => 29, 'hizb' => 59, 'verses_count' => 28, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Muzzammil', 'name_arabic' => 'المزمل', 'juz' => 29, 'hizb' => 59, 'verses_count' => 20, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Muddaththir', 'name_arabic' => 'المدثر', 'juz' => 29, 'hizb' => 59, 'verses_count' => 56, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qiyamah', 'name_arabic' => 'القيامة', 'juz' => 29, 'hizb' => 59, 'verses_count' => 40, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Insan', 'name_arabic' => 'الإنسان', 'juz' => 29, 'hizb' => 59, 'verses_count' => 31, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Mursalat', 'name_arabic' => 'المرسلات', 'juz' => 29, 'hizb' => 59, 'verses_count' => 50, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Naba', 'name_arabic' => 'النبأ', 'juz' => 30, 'hizb' => 60, 'verses_count' => 40, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Naziat', 'name_arabic' => 'النازعات', 'juz' => 30, 'hizb' => 60, 'verses_count' => 46, 'revelation_type' => 'Meccan'],
            ['name' => 'Abasa', 'name_arabic' => 'عبس', 'juz' => 30, 'hizb' => 60, 'verses_count' => 42, 'revelation_type' => 'Meccan'],
            ['name' => 'At-Takwir', 'name_arabic' => 'التكوير', 'juz' => 30, 'hizb' => 60, 'verses_count' => 29, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Infitar', 'name_arabic' => 'الانفطار', 'juz' => 30, 'hizb' => 60, 'verses_count' => 19, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Mutaffifin', 'name_arabic' => 'المطففين', 'juz' => 30, 'hizb' => 60, 'verses_count' => 36, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Inshiqaq', 'name_arabic' => 'الانشقاق', 'juz' => 30, 'hizb' => 60, 'verses_count' => 25, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Buruj', 'name_arabic' => 'البروج', 'juz' => 30, 'hizb' => 60, 'verses_count' => 22, 'revelation_type' => 'Meccan'],
            ['name' => 'At-Tariq', 'name_arabic' => 'الطارق', 'juz' => 30, 'hizb' => 60, 'verses_count' => 17, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ala', 'name_arabic' => 'الأعلى', 'juz' => 30, 'hizb' => 60, 'verses_count' => 19, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ghashiyah', 'name_arabic' => 'الغاشية', 'juz' => 30, 'hizb' => 60, 'verses_count' => 26, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Fajr', 'name_arabic' => 'الفجر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 30, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Balad', 'name_arabic' => 'البلد', 'juz' => 30, 'hizb' => 60, 'verses_count' => 20, 'revelation_type' => 'Meccan'],
            ['name' => 'Ash-Shams', 'name_arabic' => 'الشمس', 'juz' => 30, 'hizb' => 60, 'verses_count' => 15, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Layl', 'name_arabic' => 'الليل', 'juz' => 30, 'hizb' => 60, 'verses_count' => 21, 'revelation_type' => 'Meccan'],
            ['name' => 'Ad-Duha', 'name_arabic' => 'الضحى', 'juz' => 30, 'hizb' => 60, 'verses_count' => 11, 'revelation_type' => 'Meccan'],
            ['name' => 'Ash-Sharh', 'name_arabic' => 'الشرح', 'juz' => 30, 'hizb' => 60, 'verses_count' => 8, 'revelation_type' => 'Meccan'],
            ['name' => 'At-Tin', 'name_arabic' => 'التين', 'juz' => 30, 'hizb' => 60, 'verses_count' => 8, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Alaq', 'name_arabic' => 'العلق', 'juz' => 30, 'hizb' => 60, 'verses_count' => 19, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qadr', 'name_arabic' => 'القدر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 5, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Bayyinah', 'name_arabic' => 'البينة', 'juz' => 30, 'hizb' => 60, 'verses_count' => 8, 'revelation_type' => 'Medinan'],
            ['name' => 'Az-Zalzalah', 'name_arabic' => 'الزلزلة', 'juz' => 30, 'hizb' => 60, 'verses_count' => 8, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Adiyat', 'name_arabic' => 'العاديات', 'juz' => 30, 'hizb' => 60, 'verses_count' => 11, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Qariah', 'name_arabic' => 'القارعة', 'juz' => 30, 'hizb' => 60, 'verses_count' => 11, 'revelation_type' => 'Meccan'],
            ['name' => 'At-Takathur', 'name_arabic' => 'التكاثر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 8, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Asr', 'name_arabic' => 'العصر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 3, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Humazah', 'name_arabic' => 'الهمزة', 'juz' => 30, 'hizb' => 60, 'verses_count' => 9, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Fil', 'name_arabic' => 'الفيل', 'juz' => 30, 'hizb' => 60, 'verses_count' => 5, 'revelation_type' => 'Meccan'],
            ['name' => 'Quraysh', 'name_arabic' => 'قريش', 'juz' => 30, 'hizb' => 60, 'verses_count' => 4, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Maun', 'name_arabic' => 'الماعون', 'juz' => 30, 'hizb' => 60, 'verses_count' => 7, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Kawthar', 'name_arabic' => 'الكوثر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 3, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Kafirun', 'name_arabic' => 'الكافرون', 'juz' => 30, 'hizb' => 60, 'verses_count' => 6, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Nasr', 'name_arabic' => 'النصر', 'juz' => 30, 'hizb' => 60, 'verses_count' => 3, 'revelation_type' => 'Medinan'],
            ['name' => 'Al-Masad', 'name_arabic' => 'المسد', 'juz' => 30, 'hizb' => 60, 'verses_count' => 5, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Ikhlas', 'name_arabic' => 'الإخلاص', 'juz' => 30, 'hizb' => 60, 'verses_count' => 4, 'revelation_type' => 'Meccan'],
            ['name' => 'Al-Falaq', 'name_arabic' => 'الفلق', 'juz' => 30, 'hizb' => 60, 'verses_count' => 5, 'revelation_type' => 'Meccan'],
            ['name' => 'An-Nas', 'name_arabic' => 'الناس', 'juz' => 30, 'hizb' => 60, 'verses_count' => 6, 'revelation_type' => 'Meccan'],
        ];

        foreach ($surahs as $surah) {
            Surah::create($surah);
        }
    }
}
