/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MinimalRouteImport } from './routes/minimal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedMemorizationsRouteImport } from './routes/_authenticated/memorizations'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLevelsRouteImport } from './routes/_authenticated/levels'
import { Route as AuthenticatedExamResultsRouteImport } from './routes/_authenticated/exam-results'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedTeachersNewRouteImport } from './routes/_authenticated/teachers.new'
import { Route as AuthenticatedSubjectsNewRouteImport } from './routes/_authenticated/subjects.new'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students.new'
import { Route as AuthenticatedParentsNewRouteImport } from './routes/_authenticated/parents.new'
import { Route as AuthenticatedMemorizationsNewRouteImport } from './routes/_authenticated/memorizations.new'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings.new'
import { Route as AuthenticatedLevelsNewRouteImport } from './routes/_authenticated/levels.new'
import { Route as AuthenticatedExamResultsNewRouteImport } from './routes/_authenticated/exam-results.new'
import { Route as AuthenticatedClassesNewRouteImport } from './routes/_authenticated/classes.new'
import { Route as AuthenticatedAttendanceNewRouteImport } from './routes/_authenticated/attendance.new'
import { Route as AuthenticatedAnnouncementsNewRouteImport } from './routes/_authenticated/announcements.new'
import { Route as AuthenticatedTeachersIdEditRouteImport } from './routes/_authenticated/teachers.$id.edit'
import { Route as AuthenticatedSubjectsIdEditRouteImport } from './routes/_authenticated/subjects.$id.edit'
import { Route as AuthenticatedStudentsIdEditRouteImport } from './routes/_authenticated/students.$id.edit'
import { Route as AuthenticatedParentsIdEditRouteImport } from './routes/_authenticated/parents.$id.edit'
import { Route as AuthenticatedLevelsIdEditRouteImport } from './routes/_authenticated/levels.$id.edit'
import { Route as AuthenticatedClassesIdEditRouteImport } from './routes/_authenticated/classes.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalRoute = MinimalRouteImport.update({
  id: '/minimal',
  path: '/minimal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemorizationsRoute =
  AuthenticatedMemorizationsRouteImport.update({
    id: '/memorizations',
    path: '/memorizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLevelsRoute = AuthenticatedLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamResultsRoute =
  AuthenticatedExamResultsRouteImport.update({
    id: '/exam-results',
    path: '/exam-results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersNewRoute =
  AuthenticatedTeachersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedSubjectsNewRoute =
  AuthenticatedSubjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSubjectsRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedParentsNewRoute = AuthenticatedParentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedParentsRoute,
} as any)
const AuthenticatedMemorizationsNewRoute =
  AuthenticatedMemorizationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMemorizationsRoute,
  } as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedLevelsNewRoute = AuthenticatedLevelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedLevelsRoute,
} as any)
const AuthenticatedExamResultsNewRoute =
  AuthenticatedExamResultsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExamResultsRoute,
  } as any)
const AuthenticatedClassesNewRoute = AuthenticatedClassesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClassesRoute,
} as any)
const AuthenticatedAttendanceNewRoute =
  AuthenticatedAttendanceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAnnouncementsNewRoute =
  AuthenticatedAnnouncementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAnnouncementsRoute,
  } as any)
const AuthenticatedTeachersIdEditRoute =
  AuthenticatedTeachersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedSubjectsIdEditRoute =
  AuthenticatedSubjectsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedSubjectsRoute,
  } as any)
const AuthenticatedStudentsIdEditRoute =
  AuthenticatedStudentsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedParentsIdEditRoute =
  AuthenticatedParentsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedParentsRoute,
  } as any)
const AuthenticatedLevelsIdEditRoute =
  AuthenticatedLevelsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedLevelsRoute,
  } as any)
const AuthenticatedClassesIdEditRoute =
  AuthenticatedClassesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedClassesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minimal': typeof MinimalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-results': typeof AuthenticatedExamResultsRouteWithChildren
  '/levels': typeof AuthenticatedLevelsRouteWithChildren
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/memorizations': typeof AuthenticatedMemorizationsRouteWithChildren
  '/parents': typeof AuthenticatedParentsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/exam-results/new': typeof AuthenticatedExamResultsNewRoute
  '/levels/new': typeof AuthenticatedLevelsNewRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/memorizations/new': typeof AuthenticatedMemorizationsNewRoute
  '/parents/new': typeof AuthenticatedParentsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/classes/$id/edit': typeof AuthenticatedClassesIdEditRoute
  '/levels/$id/edit': typeof AuthenticatedLevelsIdEditRoute
  '/parents/$id/edit': typeof AuthenticatedParentsIdEditRoute
  '/students/$id/edit': typeof AuthenticatedStudentsIdEditRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/teachers/$id/edit': typeof AuthenticatedTeachersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minimal': typeof MinimalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-results': typeof AuthenticatedExamResultsRouteWithChildren
  '/levels': typeof AuthenticatedLevelsRouteWithChildren
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/memorizations': typeof AuthenticatedMemorizationsRouteWithChildren
  '/parents': typeof AuthenticatedParentsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/exam-results/new': typeof AuthenticatedExamResultsNewRoute
  '/levels/new': typeof AuthenticatedLevelsNewRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/memorizations/new': typeof AuthenticatedMemorizationsNewRoute
  '/parents/new': typeof AuthenticatedParentsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/classes/$id/edit': typeof AuthenticatedClassesIdEditRoute
  '/levels/$id/edit': typeof AuthenticatedLevelsIdEditRoute
  '/parents/$id/edit': typeof AuthenticatedParentsIdEditRoute
  '/students/$id/edit': typeof AuthenticatedStudentsIdEditRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/teachers/$id/edit': typeof AuthenticatedTeachersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/minimal': typeof MinimalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam-results': typeof AuthenticatedExamResultsRouteWithChildren
  '/_authenticated/levels': typeof AuthenticatedLevelsRouteWithChildren
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/_authenticated/memorizations': typeof AuthenticatedMemorizationsRouteWithChildren
  '/_authenticated/parents': typeof AuthenticatedParentsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/_authenticated/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/_authenticated/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/_authenticated/classes/new': typeof AuthenticatedClassesNewRoute
  '/_authenticated/exam-results/new': typeof AuthenticatedExamResultsNewRoute
  '/_authenticated/levels/new': typeof AuthenticatedLevelsNewRoute
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/_authenticated/memorizations/new': typeof AuthenticatedMemorizationsNewRoute
  '/_authenticated/parents/new': typeof AuthenticatedParentsNewRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/_authenticated/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/_authenticated/classes/$id/edit': typeof AuthenticatedClassesIdEditRoute
  '/_authenticated/levels/$id/edit': typeof AuthenticatedLevelsIdEditRoute
  '/_authenticated/parents/$id/edit': typeof AuthenticatedParentsIdEditRoute
  '/_authenticated/students/$id/edit': typeof AuthenticatedStudentsIdEditRoute
  '/_authenticated/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/_authenticated/teachers/$id/edit': typeof AuthenticatedTeachersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/minimal'
    | '/sitemap.xml'
    | '/announcements'
    | '/approvals'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/dashboard'
    | '/exam-results'
    | '/levels'
    | '/meetings'
    | '/memorizations'
    | '/parents'
    | '/profile'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/users'
    | '/announcements/new'
    | '/attendance/new'
    | '/classes/new'
    | '/exam-results/new'
    | '/levels/new'
    | '/meetings/new'
    | '/memorizations/new'
    | '/parents/new'
    | '/students/new'
    | '/subjects/new'
    | '/teachers/new'
    | '/classes/$id/edit'
    | '/levels/$id/edit'
    | '/parents/$id/edit'
    | '/students/$id/edit'
    | '/subjects/$id/edit'
    | '/teachers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/minimal'
    | '/sitemap.xml'
    | '/announcements'
    | '/approvals'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/dashboard'
    | '/exam-results'
    | '/levels'
    | '/meetings'
    | '/memorizations'
    | '/parents'
    | '/profile'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/users'
    | '/announcements/new'
    | '/attendance/new'
    | '/classes/new'
    | '/exam-results/new'
    | '/levels/new'
    | '/meetings/new'
    | '/memorizations/new'
    | '/parents/new'
    | '/students/new'
    | '/subjects/new'
    | '/teachers/new'
    | '/classes/$id/edit'
    | '/levels/$id/edit'
    | '/parents/$id/edit'
    | '/students/$id/edit'
    | '/subjects/$id/edit'
    | '/teachers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/minimal'
    | '/sitemap.xml'
    | '/_authenticated/announcements'
    | '/_authenticated/approvals'
    | '/_authenticated/attendance'
    | '/_authenticated/certificates'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam-results'
    | '/_authenticated/levels'
    | '/_authenticated/meetings'
    | '/_authenticated/memorizations'
    | '/_authenticated/parents'
    | '/_authenticated/profile'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/teachers'
    | '/_authenticated/users'
    | '/_authenticated/announcements/new'
    | '/_authenticated/attendance/new'
    | '/_authenticated/classes/new'
    | '/_authenticated/exam-results/new'
    | '/_authenticated/levels/new'
    | '/_authenticated/meetings/new'
    | '/_authenticated/memorizations/new'
    | '/_authenticated/parents/new'
    | '/_authenticated/students/new'
    | '/_authenticated/subjects/new'
    | '/_authenticated/teachers/new'
    | '/_authenticated/classes/$id/edit'
    | '/_authenticated/levels/$id/edit'
    | '/_authenticated/parents/$id/edit'
    | '/_authenticated/students/$id/edit'
    | '/_authenticated/subjects/$id/edit'
    | '/_authenticated/teachers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MinimalRoute: typeof MinimalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimal': {
      id: '/minimal'
      path: '/minimal'
      fullPath: '/minimal'
      preLoaderRoute: typeof MinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memorizations': {
      id: '/_authenticated/memorizations'
      path: '/memorizations'
      fullPath: '/memorizations'
      preLoaderRoute: typeof AuthenticatedMemorizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/levels': {
      id: '/_authenticated/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof AuthenticatedLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam-results': {
      id: '/_authenticated/exam-results'
      path: '/exam-results'
      fullPath: '/exam-results'
      preLoaderRoute: typeof AuthenticatedExamResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/new': {
      id: '/_authenticated/teachers/new'
      path: '/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof AuthenticatedTeachersNewRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/subjects/new': {
      id: '/_authenticated/subjects/new'
      path: '/new'
      fullPath: '/subjects/new'
      preLoaderRoute: typeof AuthenticatedSubjectsNewRouteImport
      parentRoute: typeof AuthenticatedSubjectsRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/parents/new': {
      id: '/_authenticated/parents/new'
      path: '/new'
      fullPath: '/parents/new'
      preLoaderRoute: typeof AuthenticatedParentsNewRouteImport
      parentRoute: typeof AuthenticatedParentsRoute
    }
    '/_authenticated/memorizations/new': {
      id: '/_authenticated/memorizations/new'
      path: '/new'
      fullPath: '/memorizations/new'
      preLoaderRoute: typeof AuthenticatedMemorizationsNewRouteImport
      parentRoute: typeof AuthenticatedMemorizationsRoute
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/levels/new': {
      id: '/_authenticated/levels/new'
      path: '/new'
      fullPath: '/levels/new'
      preLoaderRoute: typeof AuthenticatedLevelsNewRouteImport
      parentRoute: typeof AuthenticatedLevelsRoute
    }
    '/_authenticated/exam-results/new': {
      id: '/_authenticated/exam-results/new'
      path: '/new'
      fullPath: '/exam-results/new'
      preLoaderRoute: typeof AuthenticatedExamResultsNewRouteImport
      parentRoute: typeof AuthenticatedExamResultsRoute
    }
    '/_authenticated/classes/new': {
      id: '/_authenticated/classes/new'
      path: '/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof AuthenticatedClassesNewRouteImport
      parentRoute: typeof AuthenticatedClassesRoute
    }
    '/_authenticated/attendance/new': {
      id: '/_authenticated/attendance/new'
      path: '/new'
      fullPath: '/attendance/new'
      preLoaderRoute: typeof AuthenticatedAttendanceNewRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/announcements/new': {
      id: '/_authenticated/announcements/new'
      path: '/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AuthenticatedAnnouncementsNewRouteImport
      parentRoute: typeof AuthenticatedAnnouncementsRoute
    }
    '/_authenticated/teachers/$id/edit': {
      id: '/_authenticated/teachers/$id/edit'
      path: '/$id/edit'
      fullPath: '/teachers/$id/edit'
      preLoaderRoute: typeof AuthenticatedTeachersIdEditRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/subjects/$id/edit': {
      id: '/_authenticated/subjects/$id/edit'
      path: '/$id/edit'
      fullPath: '/subjects/$id/edit'
      preLoaderRoute: typeof AuthenticatedSubjectsIdEditRouteImport
      parentRoute: typeof AuthenticatedSubjectsRoute
    }
    '/_authenticated/students/$id/edit': {
      id: '/_authenticated/students/$id/edit'
      path: '/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AuthenticatedStudentsIdEditRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/parents/$id/edit': {
      id: '/_authenticated/parents/$id/edit'
      path: '/$id/edit'
      fullPath: '/parents/$id/edit'
      preLoaderRoute: typeof AuthenticatedParentsIdEditRouteImport
      parentRoute: typeof AuthenticatedParentsRoute
    }
    '/_authenticated/levels/$id/edit': {
      id: '/_authenticated/levels/$id/edit'
      path: '/$id/edit'
      fullPath: '/levels/$id/edit'
      preLoaderRoute: typeof AuthenticatedLevelsIdEditRouteImport
      parentRoute: typeof AuthenticatedLevelsRoute
    }
    '/_authenticated/classes/$id/edit': {
      id: '/_authenticated/classes/$id/edit'
      path: '/$id/edit'
      fullPath: '/classes/$id/edit'
      preLoaderRoute: typeof AuthenticatedClassesIdEditRouteImport
      parentRoute: typeof AuthenticatedClassesRoute
    }
  }
}

interface AuthenticatedAnnouncementsRouteChildren {
  AuthenticatedAnnouncementsNewRoute: typeof AuthenticatedAnnouncementsNewRoute
}

const AuthenticatedAnnouncementsRouteChildren: AuthenticatedAnnouncementsRouteChildren =
  {
    AuthenticatedAnnouncementsNewRoute: AuthenticatedAnnouncementsNewRoute,
  }

const AuthenticatedAnnouncementsRouteWithChildren =
  AuthenticatedAnnouncementsRoute._addFileChildren(
    AuthenticatedAnnouncementsRouteChildren,
  )

interface AuthenticatedAttendanceRouteChildren {
  AuthenticatedAttendanceNewRoute: typeof AuthenticatedAttendanceNewRoute
}

const AuthenticatedAttendanceRouteChildren: AuthenticatedAttendanceRouteChildren =
  {
    AuthenticatedAttendanceNewRoute: AuthenticatedAttendanceNewRoute,
  }

const AuthenticatedAttendanceRouteWithChildren =
  AuthenticatedAttendanceRoute._addFileChildren(
    AuthenticatedAttendanceRouteChildren,
  )

interface AuthenticatedClassesRouteChildren {
  AuthenticatedClassesNewRoute: typeof AuthenticatedClassesNewRoute
  AuthenticatedClassesIdEditRoute: typeof AuthenticatedClassesIdEditRoute
}

const AuthenticatedClassesRouteChildren: AuthenticatedClassesRouteChildren = {
  AuthenticatedClassesNewRoute: AuthenticatedClassesNewRoute,
  AuthenticatedClassesIdEditRoute: AuthenticatedClassesIdEditRoute,
}

const AuthenticatedClassesRouteWithChildren =
  AuthenticatedClassesRoute._addFileChildren(AuthenticatedClassesRouteChildren)

interface AuthenticatedExamResultsRouteChildren {
  AuthenticatedExamResultsNewRoute: typeof AuthenticatedExamResultsNewRoute
}

const AuthenticatedExamResultsRouteChildren: AuthenticatedExamResultsRouteChildren =
  {
    AuthenticatedExamResultsNewRoute: AuthenticatedExamResultsNewRoute,
  }

const AuthenticatedExamResultsRouteWithChildren =
  AuthenticatedExamResultsRoute._addFileChildren(
    AuthenticatedExamResultsRouteChildren,
  )

interface AuthenticatedLevelsRouteChildren {
  AuthenticatedLevelsNewRoute: typeof AuthenticatedLevelsNewRoute
  AuthenticatedLevelsIdEditRoute: typeof AuthenticatedLevelsIdEditRoute
}

const AuthenticatedLevelsRouteChildren: AuthenticatedLevelsRouteChildren = {
  AuthenticatedLevelsNewRoute: AuthenticatedLevelsNewRoute,
  AuthenticatedLevelsIdEditRoute: AuthenticatedLevelsIdEditRoute,
}

const AuthenticatedLevelsRouteWithChildren =
  AuthenticatedLevelsRoute._addFileChildren(AuthenticatedLevelsRouteChildren)

interface AuthenticatedMeetingsRouteChildren {
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
}

const AuthenticatedMeetingsRouteChildren: AuthenticatedMeetingsRouteChildren = {
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
}

const AuthenticatedMeetingsRouteWithChildren =
  AuthenticatedMeetingsRoute._addFileChildren(
    AuthenticatedMeetingsRouteChildren,
  )

interface AuthenticatedMemorizationsRouteChildren {
  AuthenticatedMemorizationsNewRoute: typeof AuthenticatedMemorizationsNewRoute
}

const AuthenticatedMemorizationsRouteChildren: AuthenticatedMemorizationsRouteChildren =
  {
    AuthenticatedMemorizationsNewRoute: AuthenticatedMemorizationsNewRoute,
  }

const AuthenticatedMemorizationsRouteWithChildren =
  AuthenticatedMemorizationsRoute._addFileChildren(
    AuthenticatedMemorizationsRouteChildren,
  )

interface AuthenticatedParentsRouteChildren {
  AuthenticatedParentsNewRoute: typeof AuthenticatedParentsNewRoute
  AuthenticatedParentsIdEditRoute: typeof AuthenticatedParentsIdEditRoute
}

const AuthenticatedParentsRouteChildren: AuthenticatedParentsRouteChildren = {
  AuthenticatedParentsNewRoute: AuthenticatedParentsNewRoute,
  AuthenticatedParentsIdEditRoute: AuthenticatedParentsIdEditRoute,
}

const AuthenticatedParentsRouteWithChildren =
  AuthenticatedParentsRoute._addFileChildren(AuthenticatedParentsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedStudentsIdEditRoute: typeof AuthenticatedStudentsIdEditRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedStudentsIdEditRoute: AuthenticatedStudentsIdEditRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedSubjectsRouteChildren {
  AuthenticatedSubjectsNewRoute: typeof AuthenticatedSubjectsNewRoute
  AuthenticatedSubjectsIdEditRoute: typeof AuthenticatedSubjectsIdEditRoute
}

const AuthenticatedSubjectsRouteChildren: AuthenticatedSubjectsRouteChildren = {
  AuthenticatedSubjectsNewRoute: AuthenticatedSubjectsNewRoute,
  AuthenticatedSubjectsIdEditRoute: AuthenticatedSubjectsIdEditRoute,
}

const AuthenticatedSubjectsRouteWithChildren =
  AuthenticatedSubjectsRoute._addFileChildren(
    AuthenticatedSubjectsRouteChildren,
  )

interface AuthenticatedTeachersRouteChildren {
  AuthenticatedTeachersNewRoute: typeof AuthenticatedTeachersNewRoute
  AuthenticatedTeachersIdEditRoute: typeof AuthenticatedTeachersIdEditRoute
}

const AuthenticatedTeachersRouteChildren: AuthenticatedTeachersRouteChildren = {
  AuthenticatedTeachersNewRoute: AuthenticatedTeachersNewRoute,
  AuthenticatedTeachersIdEditRoute: AuthenticatedTeachersIdEditRoute,
}

const AuthenticatedTeachersRouteWithChildren =
  AuthenticatedTeachersRoute._addFileChildren(
    AuthenticatedTeachersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRouteWithChildren
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamResultsRoute: typeof AuthenticatedExamResultsRouteWithChildren
  AuthenticatedLevelsRoute: typeof AuthenticatedLevelsRouteWithChildren
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRouteWithChildren
  AuthenticatedMemorizationsRoute: typeof AuthenticatedMemorizationsRouteWithChildren
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRouteWithChildren
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRouteWithChildren,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamResultsRoute: AuthenticatedExamResultsRouteWithChildren,
  AuthenticatedLevelsRoute: AuthenticatedLevelsRouteWithChildren,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRouteWithChildren,
  AuthenticatedMemorizationsRoute: AuthenticatedMemorizationsRouteWithChildren,
  AuthenticatedParentsRoute: AuthenticatedParentsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRouteWithChildren,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MinimalRoute: MinimalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
